### ISSUE TITLE
Channel icon is cut off

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/youtube#10]
I'll update the channel icon, so that the logo fits into the space as a whole.

![channel icon](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/632b0acf-74e8-473b-be7e-94ed278f4916)

**Comment by ripcurlx** [comment]
@ManfredKarrer Do we have some high-res versions of the icon somewhere?

**Comment by cbeams** [comment]
High(est) resolution logos I know of are at:

 - https://github.com/bisq-network/website/tree/master/images
 - https://github.com/bisq-network/website/tree/master/press-material/logos

Thanks for looking into fixing this, @ripcurlx.

**Comment by ripcurlx** [comment]
Used it from that source and updated it already. Will take a couple of minutes to propagate.

**Comment by ripcurlx** [comment]
Done.
