### ISSUE TITLE
Enrich live demo video

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/youtube#16]
I've added cards and end screen to the [video](https://youtu.be/9JW25wXnPls).
![Step 1](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/8c6ee2df-6b21-473b-9211-59254e0572ff)
![Step 2](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/ca677856-e03c-450b-a096-2fe781ecf395)
![End Screen](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/6829a2ba-bf0e-4764-83df-645347c4f6d5)

**Comment by ripcurlx** [comment]
Closing as complete.

**Comment by cbeams** [comment]
Thanks, @ripcurlx! I just updated the thumbnail and show notes as well.
