### ISSUE TITLE
Grant owner access to YouTube (Google) brand account

### ISSUE THREAD

**Issue by cbeams** [bisq-network/youtube#4]
@ManfredKarrer, you are currently the primary owner of our Google brand account for Bisq:

![image](https://user-images.githubusercontent.com/301810/34905261-5eb06a54-f855-11e7-815a-ced33264b9ba.png)

Could you please follow the instructions at https://support.google.com/youtube/answer/4628007?hl=en to add me as an owner? You can remove yourself as an owner at the same time if you wish.

The reason I am requesting this is to (a) properly reflect my status as the owner of bisq-network/roles#56, and (b) to then grant @leomcy (and potentially other contributors) access to our channel so the can upload drafts of their videos (e.g. #1) for review on their own.

**Comment by ManfredKarrer** [comment]
Done.
