### ISSUE TITLE
Produce a "How to buy bitcoin with GBP using Bisq" video

### ISSUE THREAD

**Issue by flix1** [bisq-network/youtube#5]
This task represents the second of the "how to" videos we'd like to produce. This one will explain how to buy BTC using GBP (UK Faster Payments).

This video should follow the model of the "How to buy bitcoin with Euros using Bisq". Maximum duration 5 minutes. Screencapture with voiceover. 

Video tutorial content

Part 1 - Show Accounts - Add New account - Faster Payments.
Pause

Part 2 - Show GBP order book. Click on 'I want to buy BTC with GBP'. Click on order. Complete trade.
Pause - wait for blockchain confirmation.

Part 3 - Show portfolio Open Trades. Click on ongoing trade. Offscreen - make Faster payments transfer. Explain what you did offscreen. Click on 'Confirm Payment'.
Pause - wait for seller to confirm payment received.

Part 4 - show trade completed - seller has released funds' popups. Show completed trade on History. Show security deposit has been returned. Explain order details.
End

Bounty: 200 $BSQ

**Comment by flix1** [comment]
How to buy bitcoin with Euros using Bisq
https://youtu.be/-o9CKiivyIc

**Comment by leomcy** [comment]
Ok perfect, I will take care of this

**Comment by cbeams** [comment]
@leomcy, could you please accept the invitation I sent you to join the @bisq-network GitHub organization? This will allow me to assign you to issues like this one, which is an important part of tracking who is responsible for what.

I sent the initial invitation some time ago—at least a couple weeks—so you should have email about it, but there's no need to dig for it: you should simply be able to visit https://github.com/bisq-network, where you'll see a banner near the top of the page with a link you can click to accept your invitation.

If this doesn't work as expected, or you for some reason do not wish to accept the invitation, please let me know. Thanks.

**Comment by cbeams** [comment]
This is now live. Thanks, @leomcy. From https://twitter.com/bisq_network/status/966667148339892224:

![image](https://user-images.githubusercontent.com/301810/36541238-941c8a36-17dd-11e8-9dcb-bc8f7e1e3283.png)

**Comment by flix1** [comment]
Great news! @leomcy don't forget to submit your compensation request to claim the bounty!
