### ISSUE TITLE
Produce a "How to buy bitcoin with USD using Bisq" video

### ISSUE THREAD

**Issue by flix1** [bisq-network/youtube#7]
This task represents the 4th of the "how to" videos we'd like to produce. This one will explain how to buy BTC using USD (**Zelle**).

This video should follow the model of the "How to buy bitcoin with Euros using Bisq". Maximum duration 5 minutes. Screencapture with voiceover.

Discussion is ongoing in the #youtube Slack channel now, and specific requirements and plans can be posted here to this issue.

Bounty: 200 $BSQ

**Comment by flix1** [comment]
How to buy bitcoin with Euros using Bisq
https://youtu.be/-o9CKiivyIc

**Comment by flix1** [comment]
Video tutorial content

*Part 1* - Show Accounts - Add New account - Zelle (ClearXchange).
Pause

*Part 2* - Show USD order book. Click on 'I want to buy BTC with USD'. Click on order. Complete trade.
Pause - wait for blockchain confirmation.

*Part 3* - Show portfolio Open Trades. Click on ongoing trade. Offscreen - make Zelle payment. Explain what you did offscreen. Click on 'Confirm Payment'.
Pause - wait for seller to confirm payment received.

*Part 4* - show 'trade completed - seller has released funds' popups. Show completed trade on History. Show security deposit has been returned. Explain order details.
End

**Comment by cbeams** [comment]
I'm taking this and will complete it in time for the USD liquidity week that starts on Feb 26th (bisq-network/growth#36). It can also serve as a script / template for other future how-to videos for different currency pairs.

**Comment by cbeams** [comment]
Closing as dropped / out of date
