### ISSUE TITLE
Set up and test YouTube live streaming

### ISSUE THREAD

**Issue by cbeams** [bisq-network/youtube#8]
We decided on the last growth call (bisq-network/growth#22) to do future calls via YouTube live streams on the Bisq YouTube channel, and @ripcurlx agreed to look into setting this up / getting everything ready.

@ripcurlx, I've added you as a manager of our YouTube channel (actually: our Google "brand account"), so you should have everything you need to play around with this. Let me know if you need anything else, or if I can help test it with you. Thanks.

**Comment by ripcurlx** [comment]
First test streaming event will take place at 12:30 (https://www.youtube.com/watch?v=z0AXxi0YV4Y), if someone wants to join besides @cbeams and myself ;-)

**Comment by ripcurlx** [comment]
We have tested the abilities of Google Hangout on Air and it seems to work for our growth call. Unlimited users can watch and add comments during the live video and up to 25 people can join the Google Hangout itself: https://github.com/bisq-network/growth/issues/33

**Comment by cbeams** [comment]
Closing as complete. Thanks, @ripcurlx!

**Comment by cbeams** [comment]
Acutally closing; clicked the wrong button last time.
