### ISSUE TITLE
Produce a "How to buy bitcoin with INR using Bisq" video

### ISSUE THREAD

**Issue by flix1** [bisq-network/youtube#9]
This task represents the 4th of the "how to" videos we'd like to produce. This one will explain how to buy BTC using INR.

This video should follow the model of the "How to buy bitcoin with Euros using Bisq". Maximum duration 5 minutes. Screencapture with voiceover.

Discussion is ongoing in the #youtube Slack channel now, and specific requirements and plans can be posted here to this issue.

Video tutorial content

Part 1 - Show Accounts - Add New account - National Bank Transfer- India.
Pause

Part 2 - Show INR order book. Click on 'I want to buy BTC with INR'. Click on order. Complete trade.
Pause - wait for blockchain confirmation.

Part 3 - Show portfolio Open Trades. Click on ongoing trade. Offscreen - make Bank payment. Explain what you did offscreen. Click on 'Confirm Payment'.
Pause - wait for seller to confirm payment received.

Part 4 - show 'trade completed - seller has released funds' popups. Show completed trade on History. Show security deposit has been returned. Explain order details.
End

Bounty: 200 $BSQ

**Comment by flix1** [comment]
As an experiment I have posted this as a project on freelancer.com.

**Comment by flix1** [comment]
-I had quite a lot of bids on this project at freelancer.com. 
-I awarded the project to one with video editing skills.
-I am very much regretting it!

The time it is taking me to explain everything and walk him through how to use Bisq is more work than if I had done everything myself. So far I don't think it's worth the money. We'll see what the result is like...

**Comment by cbeams** [comment]
Sounds like a good experiment / lesson in any case. I think the best thing we can do is find someone reasonably skilled with screencasting, basic video editing, who has an engaging voice, a decent sound setup and—most importantly—**is quite familiar with Bisq** and enthusiastic to see it succeed. 

We ultimately want a small group of motivated specialists who are _pulling_ to do these screencasts and videos, not a large group of generalists who are being _pushed_ the work.

But casting a wide net right now (via Twitter, freelancer.com) is a reasonable thing to do to see if we can find such individuals. Perhaps the freelancer.com route won't work in the end, but I'm glad you tried!

**Comment by flix1** [comment]
Agreed. It's easier to teach someone who knows Bisq and Bitcoin to record a screencap and do a voiceover than the other way around.

But there is a bit of a chicken and egg problem in many countries where Bisq is unheard of... and the video tutorials can help with that.

**Comment by flix1** [comment]
Video is complete. Sending to @cbeams now.

I'm not very satisfied with this experiment. Too slow, too expensive and too much direction was needed. I won't be using freelancer.com again for this type of stuff.

It was worth a try...

**Comment by cbeams** [comment]
Got it, thanks. Will review asap.

**Comment by cbeams** [comment]
Closing as complete. Thanks @flix1. This came out better than I thought it would, but we can do better. Maybe I should bite the bullet and record the video for $BTC / $USD and then we can use that as a baseline for all future videos that differ only in currency. That way we'd get exactly the wording and presentation we want, and others can just follow suit, modifying only as necessary for their locale.

From https://twitter.com/bisq_network/status/958676488609464320:

![image](https://user-images.githubusercontent.com/301810/35623213-0633376e-068b-11e8-8c29-f31869122671.png)

**Comment by cbeams** [comment]
One last thing, @flix1: what did this video cost you to produce? Would be good to know what the going rate was for this kind of work on freelancer.com. Thanks.

**Comment by flix1** [comment]
I agree that we can definitely do better.

The freelancer.com project cost me 160€, although I think that I overpaid out of impatience and inexperience. From the bids received I believe I could have obtained a similar result for about half that... or $90-100.

In fact I had lower bids but decided to choose one from a freelancer based in India. I will post a few screenshots in slack.
